# Generated by Django 5.0.7 on 2025-10-09 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('height', models.FloatField(blank=True, help_text='Height in cm', null=True)),
                ('weight', models.FloatField(blank=True, help_text='Current weight in kg', null=True)),
                ('target_weight', models.FloatField(blank=True, help_text='Target weight in kg', null=True)),
                ('calories', models.FloatField(default=0.0)),
                ('protein', models.FloatField(default=0.0)),
                ('carbs', models.FloatField(default=0.0)),
                ('fat', models.FloatField(default=0.0)),
                ('calories_burned', models.FloatField(default=0.0)),
                ('goal', models.CharField(blank=True, choices=[('Cut', 'Cut'), ('Bulk', 'Bulk'), ('Recomposition', 'Recomposition'), ('Abs', 'Abs Training'), ('Maintain', 'Maintain')], max_length=50, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('weekly_weight_data', models.JSONField(default=list, help_text='Historical weight and calories burned per day')),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_method', models.CharField(choices=[('email', 'Email'), ('mobile', 'Mobile')], default='email', max_length=10)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('email_token', models.CharField(blank=True, max_length=64, null=True)),
                ('otp_timestamp', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('Cut', 'Cut'), ('Bulk', 'Bulk'), ('Recomposition', 'Recomposition'), ('Abs', 'Abs Training'), ('Maintain', 'Maintain')], max_length=20)),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('exercise', models.CharField(max_length=100)),
                ('sets', models.CharField(max_length=50)),
                ('reps', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['goal', 'day_of_week'],
                'unique_together': {('goal', 'day_of_week', 'exercise')},
            },
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('meal_time', models.CharField(max_length=20)),
                ('items', models.TextField()),
                ('calories', models.IntegerField()),
                ('protein', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fat', models.FloatField()),
                ('goal', models.CharField(choices=[('Cut', 'Cut'), ('Bulk', 'Bulk'), ('Recomposition', 'Recomposition'), ('Abs', 'Abs Training'), ('Maintain', 'Maintain')], max_length=20)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to='core.userprofile')),
            ],
            options={
                'ordering': ['user_profile', 'goal', 'day'],
                'unique_together': {('user_profile', 'goal', 'day', 'meal_time')},
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('exercise', models.CharField(max_length=100)),
                ('sets', models.CharField(max_length=50)),
                ('reps', models.CharField(max_length=50)),
                ('goal', models.CharField(choices=[('Cut', 'Cut'), ('Bulk', 'Bulk'), ('Recomposition', 'Recomposition'), ('Abs', 'Abs Training'), ('Maintain', 'Maintain')], max_length=20)),
                ('duration', models.IntegerField(default=30, help_text='Duration in minutes')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='core.userprofile')),
            ],
            options={
                'ordering': ['user_profile', 'goal', 'day'],
                'unique_together': {('user_profile', 'goal', 'day', 'exercise')},
            },
        ),
    ]
